title: My Blog
author: Eric Payne
email: duncecapsoftware@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dunce Cap Software's Home Page!

# social links
twitter_username: erdapa
github_username:  erdapa

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
